import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import { Kosugi } from "next/font/google"

const mmcFonts = localFont({
  src: [
    {
      path: "../../public/fonts/MMCRegular.woff",
      weight: "100 400",
      style: "normal",
    },
    {
      path: "../../public/fonts/MMCMedium.woff",
      weight: "500 600",
      style: "medium",
    },
    {
      path: "../../public/fonts/MMCBold.woff",
      weight: "700 900",
      style: "bold",
    },
  ],
})

const kosugi = Kosugi({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-kosugi",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${mmcFonts.className} ${kosugi.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
